use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use fst::{Map, MapBuilder, Set, SetBuilder};

const UPSTREAM_REVISION: &str = "5907b4739793b3d5d7061eaa3f85274e09769d6a";

fn main() -> Result<(), Box<dyn Error>> {
    let args: Vec<String> = env::args().collect();
    match args.get(1).map(String::as_str) {
        None => print_zig_fixtures(),
        Some("check-zig") => check_zig(),
        Some(arg) => Err(format!("unknown subcommand: {arg}").into()),
    }
}

fn print_zig_fixtures() -> Result<(), Box<dyn Error>> {
    println!("// Generated by:");
    println!("// cargo run --manifest-path tools/fysti-rust-fixtures/Cargo.toml");
    println!("// Upstream BurntSushi/fst revision: {UPSTREAM_REVISION}");
    println!();

    print_decl("rust_set_fixture", &build_set(&[b"a", b"ab", b"b"])?);
    print_decl(
        "rust_map_fixture",
        &build_map(&[(b"a", 1), (b"ab", 3), (b"b", 10)])?,
    );
    print_decl(
        "rust_prefix_final_map_fixture",
        &build_map(&[(b"a", 10), (b"ab", 3), (b"b", 20)])?,
    );
    print_decl("rust_direct_index_set_fixture", &build_direct_index_set()?);

    Ok(())
}

fn build_set(keys: &[&[u8]]) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut builder = SetBuilder::memory();
    for key in keys {
        builder.insert(key)?;
    }
    Ok(builder.into_inner()?)
}

fn build_map(entries: &[(&[u8], u64)]) -> Result<Vec<u8>, Box<dyn Error>> {
    let mut builder = MapBuilder::memory();
    for (key, value) in entries {
        builder.insert(key, *value)?;
    }
    Ok(builder.into_inner()?)
}

fn build_direct_index_set() -> Result<Vec<u8>, Box<dyn Error>> {
    let keys: Vec<Vec<u8>> = (0u8..33).map(|offset| vec![0x21 + offset]).collect();
    let refs: Vec<&[u8]> = keys.iter().map(Vec::as_slice).collect();
    let bytes = build_set(&refs)?;
    Set::new(bytes.clone())?.as_fst().verify()?;
    Ok(bytes)
}

fn print_decl(name: &str, bytes: &[u8]) {
    println!("/// Rust-written fixture generated from BurntSushi/fst {UPSTREAM_REVISION}.");
    println!("pub const {name}: []const u8 = &.{{");
    for chunk in bytes.chunks(12) {
        print!("   ");
        for byte in chunk {
            print!(" 0x{byte:02x},");
        }
        println!();
    }
    println!("}};");
    println!();
}

fn check_zig() -> Result<(), Box<dyn Error>> {
    let repo_root = repo_root()?;
    let temp_dir = env::temp_dir().join(format!("fysti-zig-fixtures-{}", std::process::id()));
    fs::create_dir_all(&temp_dir)?;

    let set_path = temp_dir.join("zig-set.fst");
    let map_path = temp_dir.join("zig-map.fst");
    let status = Command::new("zig")
        .current_dir(&repo_root)
        .args([
            "run",
            "--dep",
            "fysti",
            "-Mroot=tools/fysti-rust-fixtures/write_zig_fixtures.zig",
            "-Mfysti=src/fysti.zig",
            "--",
        ])
        .arg(&set_path)
        .arg(&map_path)
        .status()?;
    if !status.success() {
        return Err(format!("zig fixture writer failed with status {status}").into());
    }

    check_zig_set(&set_path)?;
    check_zig_map(&map_path)?;
    println!("zig-written fixtures readable by Rust fst");
    Ok(())
}

fn repo_root() -> Result<PathBuf, Box<dyn Error>> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    Ok(manifest_dir
        .parent()
        .and_then(Path::parent)
        .ok_or("helper crate must live under tools/fysti-rust-fixtures")?
        .to_path_buf())
}

fn check_zig_set(path: &Path) -> Result<(), Box<dyn Error>> {
    let bytes = fs::read(path)?;
    let set = Set::new(bytes)?;
    set.as_fst().verify()?;
    assert!(set.contains(""));
    assert!(set.contains("ant"));
    assert!(set.contains("cat"));
    assert!(set.contains("dog"));
    assert!(!set.contains("cow"));
    Ok(())
}

fn check_zig_map(path: &Path) -> Result<(), Box<dyn Error>> {
    let bytes = fs::read(path)?;
    let map = Map::new(bytes)?;
    map.as_fst().verify()?;
    assert_eq!(map.get(""), Some(7));
    assert_eq!(map.get("ant"), Some(10));
    assert_eq!(map.get("cat"), Some(13));
    assert_eq!(map.get("dog"), Some(21));
    assert_eq!(map.get("cow"), None);
    Ok(())
}
